dashboard_leaf/blueprints/Routes.py
from flask import Blueprint, render_template

from logic.page import PageManager


def construct_blueprint(settings, pageManager: PageManager):
    routes = Blueprint('routes', __name__)

    @routes.get('/')
    def index():
        pageNames = pageManager.get_all_available_page_names()
        return render_template('index.html', pageNames=pageNames)

    @routes.get('/page/<pageName>')
    def show_page(pageName: str):
        pageInstance = pageManager.get_page_instance_by_name(pageName)
        return render_template('page.html', page=pageInstance)

    return routes

dashboard_leaf/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>DashboardLeaf</title>
        {% import 'macros.html' as macros %}
        {{ macros.header(true) }}
    </head>

    <body>
        <div class="main">
            <div class="content">
                <h2>Available Pages</h2>
                <div class="spacer"></div>
                {% for name in pageNames %}
                    <a class="page-item" href="{{ url_for("routes.show_page", pageName=name) }}">{{ name }}</a>
                {% endfor %}
            </div>
        </div>
    </body>
    <script type="text/javascript" src={{ url_for('static', filename='js/main.js') }}></script>
</html>

dashboard_leaf/templates/macros.html
{% macro header(addViewport) -%}
    <meta charset="UTF-8"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{{ url_for('static', filename='libraries/fontawesome/css/all.min.css') }}" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>

    <link rel="apple-touch-icon" href="{{ url_for('static', filename='touch_icon.png') }}">

    {% if addViewport %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% endif%}
{%- endmacro %}

dashboard_leaf/templates/page.html
<!DOCTYPE html>
<html>
    <head>
        <title>DashboardLeaf</title>

        {% import 'macros.html' as macros %}
        {{ macros.header(false) }}

        <script src="../static/js/libs/socket.io.min.js"></script>
        <script src="../static/js/libs/gridstack.min.js"></script>
        <script src="../static/js/libs/plotly.min.js"></script>
        <script src="../static/js/libs/plotly.locale.de.min.js"></script>

        <link type="text/css" rel="stylesheet" href="../static/css/libs/weather-icons.min.css" />
        <link type="text/css" rel="stylesheet" href="../static/css/libs/weather-icons-wind.min.css" />
        <link type="text/css" rel="stylesheet" href="../static/css/libs/gridstack.min.css" />
    </head>
    <body>
        <div class="grid-stack">
            {% for tileName, tileLayoutSettings in page.get_tile_layouts_sorted().items() %}
                <div class="grid-stack-item"
                     id="tile-{{ page.uniqueName | replace(' ', '_') }}_{{ tileName }}"
                     data-gs-x="{{ tileLayoutSettings.x }}" data-gs-y="{{ tileLayoutSettings.y }}"
                     data-gs-width="{{ tileLayoutSettings.width }}" data-gs-height="{{ tileLayoutSettings.height }}">
                    <div class="grid-stack-item-content">
                        <div class="container">
                            <!-- content will be inserted here -->
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <script src="../static/js/main.js"></script>
    </body>
</html>